const date = new Date();
console.log(+date);
console.log(date.getFullYear());
console.log(date.getMonth());
console.log(date.getDay());
const userDOB = new Date("2024-09-22");
console.log(+userDOB);
console.log(userDOB.getFullYear());
console.log(userDOB.getMonth()+1);
console.log(userDOB.getDay());